import { CountryHeat, Trend } from "@/lib/types";

export const trends: Trend[] = [
  {
    id: "ai-music-agents",
    name: "AI Music Agents",
    category: "Musikk",
    country: "USA",
    region: "Nord-Amerika",
    growthPercent: 148.2,
    trendScore: 93,
    strength: 91,
    sparkline: [38, 41, 44, 52, 60, 71, 85, 96],
    watchedBy: 2194,
    launchedHoursAgo: 18,
    growth24h: 31.2,
    growth7d: 98.5,
    growth30d: 148.2,
    aiSummary:
      "Nye verktøy for AI-generert musikk kombineres med creator-okonomi pa korte videoformater. Det gir rask spredning i USA, Canada og Storbritannia.",
    sources: [
      { title: "Reddit: r/WeAreTheMusicMakers", url: "https://reddit.com", sourceType: "Reddit" },
      { title: "YouTube trendkanaler", url: "https://youtube.com", sourceType: "YouTube" },
      { title: "Tech-magasin dekning", url: "https://example.com", sourceType: "Nyheter" },
    ],
  },
  {
    id: "retro-gaming-handhelds",
    name: "Retro Gaming Handhelds",
    category: "Spill",
    country: "Japan",
    region: "Asia",
    growthPercent: 121.4,
    trendScore: 88,
    strength: 84,
    sparkline: [30, 33, 37, 45, 54, 63, 72, 82],
    watchedBy: 1450,
    launchedHoursAgo: 36,
    growth24h: 24.3,
    growth7d: 80.1,
    growth30d: 121.4,
    aiSummary:
      "Kombinasjonen av nostalgi, samleobjekter og nye indie-utgivelser driver kraftig vekst i Japan og Sor-Korea.",
    sources: [
      { title: "Forum: RetroGamer boards", url: "https://example.com", sourceType: "Forum" },
      { title: "YouTube: Handheld reviews", url: "https://youtube.com", sourceType: "YouTube" },
      { title: "Trendmotor intern signalpakke", url: "https://example.com", sourceType: "Trendmotor" },
    ],
  },
  {
    id: "nordic-blues-wave",
    name: "Nordic Blues Wave",
    category: "Musikk",
    country: "Sverige",
    region: "Europa",
    growthPercent: 94.6,
    trendScore: 82,
    strength: 73,
    sparkline: [28, 30, 31, 35, 40, 49, 57, 66],
    watchedBy: 1198,
    launchedHoursAgo: 62,
    growth24h: 16.8,
    growth7d: 58.4,
    growth30d: 94.6,
    aiSummary:
      "Live-klipp pa sosiale medier og samarbeid mellom nisjeartister skaper ny interesse for moderne nordisk blues.",
    sources: [
      { title: "Reddit: r/Blues", url: "https://reddit.com", sourceType: "Reddit" },
      { title: "Nyhetsbrev for livescener", url: "https://example.com", sourceType: "Nyheter" },
    ],
  },
  {
    id: "micro-wellness-habits",
    name: "Micro Wellness Habits",
    category: "Helse",
    country: "Brasil",
    region: "Sor-Amerika",
    growthPercent: 109.1,
    trendScore: 86,
    strength: 78,
    sparkline: [24, 26, 29, 34, 43, 55, 67, 73],
    watchedBy: 980,
    launchedHoursAgo: 20,
    growth24h: 28.9,
    growth7d: 69.2,
    growth30d: 109.1,
    aiSummary:
      "Korte, daglige rutiner for stressmestring deles i hoyt tempo pa video og meldingsplattformer i Brasil og Mexico.",
    sources: [
      { title: "YouTube shorts om helse", url: "https://youtube.com", sourceType: "YouTube" },
      { title: "Forum for livsstilscoacher", url: "https://example.com", sourceType: "Forum" },
    ],
  },
  {
    id: "silent-luxury-techwear",
    name: "Silent Luxury Techwear",
    category: "Mote",
    country: "Italia",
    region: "Europa",
    growthPercent: 76.8,
    trendScore: 79,
    strength: 69,
    sparkline: [20, 22, 24, 30, 37, 43, 51, 58],
    watchedBy: 890,
    launchedHoursAgo: 44,
    growth24h: 14.4,
    growth7d: 43.8,
    growth30d: 76.8,
    aiSummary:
      "Diskrete premium-plagg med tekniske materialer far oppmerksomhet gjennom moteuker og influencer-redaksjoner.",
    sources: [
      { title: "Nyheter: moteanalyse", url: "https://example.com", sourceType: "Nyheter" },
      { title: "Reddit: r/malefashionadvice", url: "https://reddit.com", sourceType: "Reddit" },
    ],
  },
  {
    id: "social-shopping-live",
    name: "Social Shopping Live",
    category: "Sosiale medier",
    country: "Indonesia",
    region: "Asia",
    growthPercent: 132.7,
    trendScore: 90,
    strength: 89,
    sparkline: [31, 35, 39, 46, 58, 68, 80, 92],
    watchedBy: 2012,
    launchedHoursAgo: 9,
    growth24h: 36.1,
    growth7d: 88.6,
    growth30d: 132.7,
    aiSummary:
      "Direktesending med kjop i app skalerer raskt pa tvers av byer i Sorost-Asia med hoy konvertering pa lavprisprodukter.",
    sources: [
      { title: "Trendmotor handelssignal", url: "https://example.com", sourceType: "Trendmotor" },
      { title: "YouTube creators i regionen", url: "https://youtube.com", sourceType: "YouTube" },
    ],
  },
  {
    id: "climate-smart-food",
    name: "Climate Smart Food",
    category: "Mat",
    country: "Kenya",
    region: "Afrika",
    growthPercent: 88.3,
    trendScore: 81,
    strength: 67,
    sparkline: [18, 21, 24, 29, 33, 41, 47, 55],
    watchedBy: 640,
    launchedHoursAgo: 73,
    growth24h: 12.4,
    growth7d: 39.7,
    growth30d: 88.3,
    aiSummary:
      "Innhold om lokale, robuste matvarer far sterk spredning gjennom utdanningsprofiler og samfunnsinitiativer.",
    sources: [
      { title: "Nyheter: matsikkerhet", url: "https://example.com", sourceType: "Nyheter" },
      { title: "Forum for urban farming", url: "https://example.com", sourceType: "Forum" },
    ],
  },
  {
    id: "coastal-running-clubs",
    name: "Coastal Running Clubs",
    category: "Sport",
    country: "Australia",
    region: "Oseania",
    growthPercent: 67.5,
    trendScore: 74,
    strength: 61,
    sparkline: [16, 18, 20, 25, 31, 35, 42, 49],
    watchedBy: 522,
    launchedHoursAgo: 95,
    growth24h: 9.3,
    growth7d: 28.4,
    growth30d: 67.5,
    aiSummary:
      "Sosiale lopemiljoer med fokus pa kystnare opplevelser vokser jevnt gjennom arrangementer og korte video-oppsummeringer.",
    sources: [{ title: "Sosiale forum for loping", url: "https://example.com", sourceType: "Forum" }],
  },
];

export const countryHeat: CountryHeat[] = [
  { country: "USA", code: "US", x: 21, y: 38, heat: 94, label: "AI Music", featuredTrends: ["AI Music Agents", "Social Shopping Live"] },
  { country: "Canada", code: "CA", x: 20, y: 26, heat: 68, label: "Creator Tools", featuredTrends: ["AI Music Agents"] },
  { country: "Brasil", code: "BR", x: 33, y: 62, heat: 79, label: "Micro Wellness", featuredTrends: ["Micro Wellness Habits"] },
  { country: "Sverige", code: "SE", x: 51, y: 26, heat: 73, label: "Nordisk Blues", featuredTrends: ["Nordic Blues Wave"] },
  { country: "Italia", code: "IT", x: 53, y: 35, heat: 65, label: "Techwear", featuredTrends: ["Silent Luxury Techwear"] },
  { country: "Kenya", code: "KE", x: 58, y: 56, heat: 61, label: "Smart Food", featuredTrends: ["Climate Smart Food"] },
  { country: "Japan", code: "JP", x: 81, y: 38, heat: 91, label: "Retro Gaming", featuredTrends: ["Retro Gaming Handhelds"] },
  { country: "Indonesia", code: "ID", x: 77, y: 54, heat: 89, label: "Live Commerce", featuredTrends: ["Social Shopping Live"] },
  { country: "Australia", code: "AU", x: 84, y: 73, heat: 58, label: "Run Clubs", featuredTrends: ["Coastal Running Clubs"] },
];

export const regions = [
  "Hele verden",
  "Europa",
  "Nord-Amerika",
  "Sor-Amerika",
  "Asia",
  "Afrika",
  "Oseania",
] as const;

export const categories = [
  "Musikk",
  "Teknologi",
  "Spill",
  "Mote",
  "Mat",
  "Livsstil",
  "Sosiale medier",
  "Sport",
  "Helse",
] as const;
